// Generated by CoffeeScript 1.3.3
(function() {
  var ScrollView,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  ScrollView = (function() {

    function ScrollView(element) {
      this.click = __bind(this.click, this);
      this.element = $(element);
      this.make_scroller();
      this.make_switch();
    }

    ScrollView.prototype.click = function(event) {
      var index, target;
      this.switch_element.find("li").removeClass("selected");
      target = $(event.target);
      index = target.attr("data-index");
      target.parent().addClass("selected");
      TweenLite.to(this.element.find(".screen"), .8, {
        "css": {
          "left": index * this.width * (-1)
        },
        "ease": Power4.easeOut
      });
      return false;
    };

    ScrollView.prototype.make_switch = function() {
      var count, id, index, link, _i, _ref, _results;
      count = this.element.find(".view").length;
      id = this.element.attr("data-for");
      this.switch_element = $("#" + id);
      _results = [];
      for (index = _i = 0, _ref = count - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; index = 0 <= _ref ? ++_i : --_i) {
        link = $("<a>", {
          "data-index": index,
          "href": "#"
        });
        link.click(this.click);
        _results.push(this.switch_element.append($("<li>", {
          "class": (index === 0 ? "selected" : "")
        }).append(link)));
      }
      return _results;
    };

    ScrollView.prototype.make_scroller = function() {
      var views;
      views = this.element.find(".view");
      this.width = $(views[0]).width();
      this.element.width(this.width);
      views.width(this.width);
      this.element.find(".screen").width(views.length * this.width);
      views.css("float", "left");
      return views.show();
    };

    return ScrollView;

  })();

  $(function() {
    var _this = this;
    $(".scroller").each(function(index, element) {
      return new ScrollView(element);
    });
    if (window.location.href.search(/par-slov/) !== -1) {
      return $("header nav li:nth-child(2)").addClass("selected");
    } else if (window.location.href.search(/reference/) !== -1) {
      return $("header nav li:nth-child(3)").addClass("selected");
    } else if (window.location.href.search(/galerie/) !== -1) {
      return $("header nav li:nth-child(6)").addClass("selected");
    } else if (window.location.href.search(/kontakt/) !== -1) {
      return $("header nav li:nth-child(4)").addClass("selected");
    }
  });

}).call(this);
